CREATE DATABASE IF NOT EXISTS `Resturant`
USE `Resturant`


DROP TABLE IF EXISTS `Menu`;


CREATE TABLE `Menu` (
    `ITEM_ID` int(10) NOT NULL AUTO_INCREMENT,
    `ITEM_NAME` varchar(50) DEFAULT NULL,
    `PRICE` double DEFAULT NULL,
    PRIMARY KEY (`ITEM_ID`)
)ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8;
